Fix build error from commit 3da446303432e640c4c8240bbb2404f7c5dad97d
frameworks/av/media/libmediaplayerservice/StagefrightRecorder.cpp:1465:20:
error: 'PROPERTY_VALUE_MAX' was not declared in this scope
frameworks/av/media/libmediaplayerservice/StagefrightRecorder.cpp:1466:57:
error: 'value' was not declared in this scope
frameworks/av/media/libmediaplayerservice/StagefrightRecorder.cpp:1466:70:
error: 'property_get' was not declared in this scope
make: *** [/android/mydroid-cm10/out/target/product/xt926/obj/
SHARED_LIBRARIES/libmediaplayerservice_intermediates/StagefrightRecorder.o]
Error 1

Change-Id: I346300231f977082314b05e09184ea519b50c719