Revert "libstagefright: remove left shifts causing unsigned int overflow"
Causing the following build breakage:

frameworks/av/media/libstagefright/codecs/mp3dec/src/pvmp3_get_side_info.cpp:113:58: error: suggest parentheses around '-' inside '<<' [-Werror=parentheses]
 #define mask_and_shift(tmp, a, b) ((tmp >> (b - a)) & (1 << (32 - b) - 1))
                                                          ^
frameworks/av/media/libstagefright/codecs/mp3dec/src/pvmp3_get_side_info.cpp:222:52: note: in expansion of macro 'mask_and_shift'
             si->ch[ch].gran[0].part2_3_length    = mask_and_shift(tmp, 11, 20);   /* 12 */
                                                    ^
frameworks/av/media/libstagefright/codecs/mp3dec/src/pvmp3_get_side_info.cpp:113:58: error: suggest parentheses around '-' inside '<<' [-Werror=parentheses]
 #define mask_and_shift(tmp, a, b) ((tmp >> (b - a)) & (1 << (32 - b) - 1))
                                                          ^
frameworks/av/media/libstagefright/codecs/mp3dec/src/pvmp3_get_side_info.cpp:223:52: note: in expansion of macro 'mask_and_shift'
             si->ch[ch].gran[0].big_values        = mask_and_shift(tmp, 23, 23);   /*  9 */
                                                    ^

This reverts commit 18d5c836b74fa6e74806c8fb30bf33b7caeaabac.

Change-Id: I64fc05f92ffb22b79575ecc978d8b2bc2a95c5cc